import type { Metadata } from "next";
import { OnboardingNavbar } from "@/components/onboarding/navbar/navbar";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <OnboardingNavbar enableSidebar={false}
            />
            {children}
        </>
    );
}
